### ISSUE TITLE
Hide clear label

### ISSUE THREAD

**Issue by HBrianL** [xamarin/SignaturePad#100]
Hi, how I can hide the clear label. I'm trying this:
signature.ClearLabel.IsVisible = false;

But doesn't work.

Thanks!

**Comment by christianlouislivioco** [comment]
signature.ClearText = string.Empty;

**Comment by mattleibow** [comment]
Removing the clear label may mean that you are not wanting all the bits. You can check out the `SignaturePadCanvasView`.

This is basically the real signature pad control, but without all the buttons and labels. You can still use all the features of writing signatures and saving, but it has to be done programmatically.

**Comment by mattleibow** [comment]
This is not really a feature that we would implement, unless there is a high demand (which can be shown by voting on the issue).

If you want to control the chrome, you should make use of the chrome-less `SignaturePadCanvasView` and listen to the events.

`SignaturePadView` is really a very small layer over the `SignaturePadCanvasView`, and just listens to the `StrokeCompleted` event. All the other events and methods are available on the canvas.
