### ISSUE TITLE
Fit the control to the background image

### ISSUE THREAD

**Issue by Manu404** [xamarin/SignaturePad#101]
Hi,

I'm using your control to draw over an image. In our app, the client can take photo and need after to draw indications on the photo.

Your control is nice but I still have one problem.

I set the background image to the image the user need to draw on.

Is there anyway I can fit the control to the background image ? Because actually it's possible to draw outside the image if the background image don't fit the control. I need to keep the aspect ratio of my image.

I'm using the v2.2 for Xamarin Forms

Best regards.

**Comment by Manu404** [comment]
I found a solution using SignaturePadCanvasView and binding HeighRequest and WidthRequest to the Height and Width of the other control3

**Comment by praveennachi60** [comment]
Hey @Manu404 ,
Can you please explain me how you solved your issue??
How to use signaturepadvcanvasview? Im facing the same problem.

**Comment by Manu404** [comment]
> 
> 
> Hey @Manu404 ,
> Can you please explain me how you solved your issue??
> How to use signaturepadvcanvasview? Im facing the same problem.

Hi, 

don't work on xamarin forms anymore, nor at that company, but I added this before closing  the issue: I found a solution using SignaturePadCanvasView and binding HeighRequest and WidthRequest to the Height and Width of the other control3

But I sincerely can't help you more sadly :(
