### ISSUE TITLE
MVVM - Clear Signature

### ISSUE THREAD

**Issue by TheRealSteveJudge** [xamarin/SignaturePad#107]
Hi,

it might be a good idea to have a Points or Strokes Dependency Property to make it possible to clear the Points or Strokes made when using MVVM.

**Comment by mattleibow** [comment]
This is related to #120

**Comment by mattleibow** [comment]
And #109

**Comment by mattleibow** [comment]
Closing this issue as I am moving this discussion to the more general #133 issue.
