### ISSUE TITLE
signature pad not able to show on release mode

### ISSUE THREAD

**Issue by starking1017** [xamarin/SignaturePad#108]
Hi,
I use the signaturePad in xamarin.forms. Everything works perfectly in debug mode. When I try to build as release mode. App will crash. (Android)

Do I miss anything? or
Does anyone have the same situation or anyone know how to resolve it? 

I use latest version of xamarin and signaturepad 2.3.0.

some possible error trace:
`Xamarin caused by: android.runtime.JavaProxyThrowable: System.InvalidCastException: Specified cast is not valid.
System.Object.__castclass_with_cache(object, intptr, intptr)(wrapper castclass)
Xamarin.Forms.Internals.Registrar<TRegistrable>.GetHandler(Type type)<1feef6e00a314921bf9a29876c83b540>:0
Xamarin.Forms.Internals.Registrar<TRegistrable>.GetHandler(Type type, object[] args)<1feef6e00a314921bf9a29876c83b540>:0
Xamarin.Forms.Internals.Registrar<TRegistrable>.GetHandler<TOut>(Type type, object[] args)<1feef6e00a314921bf9a29876c83b540>:0
Xamarin.Forms.Platform.Android.Platform.CreateRenderer(VisualElement element, Context context)<b5b1173f4d49442b898c45e26ae39e48>:0
Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild(VisualElement view, IVisualElementRenderer oldRenderer, RendererPool pool, bool sameChildren)<b5b1173f4d49442b898c45e26ae39e48>:0
Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement(VisualElement oldElement, VisualElement newElement)<b5b1173f4d49442b898c45e26ae39e48>:0
Xamarin.Forms.Platform.Android.VisualElementPackager.Load()<b5b1173f4d49442b898c45e26ae39e48>:0
Xamarin.Forms.Platform.Android.VisualElementRenderer<TElement>.SetPackager(VisualElementPackager packager)<b5b1173f4d49442b898c45e26ae39e48>:0
Xamarin.Forms.Platform.Android.VisualElementRenderer<TElement>.SetElement(TElement element)<b5b1173f4d49442b898c45e26ae39e48>:0
Xamarin.Forms.Platform.Android.VisualElementRenderer<TElement>.SetElement(VisualElement element)<b5b1173f4d49442b898c45e26ae39e48>:0
Xamarin.Forms.Platform.Android.Platform.CreateRenderer(VisualElement element, Context context)<b5b1173f4d49442b898c45e26ae39e48>:0
Xamarin.Forms.Platform.Android.ScrollViewContainer.set_ChildView(View value)<b5b1173f4d49442b898c45e26ae39e48>:0
Xamarin.Forms.Platform.Android.ScrollViewRenderer.LoadContent()<b5b1173f4d49442b898c45e26ae39e48>:0
Xamarin.Forms.Platform.Android.ScrollViewRenderer.SetElement(VisualElement element)<b5b1173f4d49442b898c45e26ae39e48>:0
Xamarin.Forms.Platform.Android.Platform.CreateRenderer(VisualElement element, Context context)<b5b1173f4d49442b898c45e26ae39e48>:0
Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild(VisualElement view, IVisualElementRenderer oldRenderer, RendererPool pool, bool sameChildren)<b5b1173f4d49442b898c45e26ae39e48>:0
Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement(VisualElement oldElement, VisualElement newElement)<b5b1173f4d49442b898c45e26ae39e48>:0
Xamarin.Forms.Platform.Android.VisualElementPackager.Load()<b5b1173f4d49442b898c45e26ae39e48>:0
Xamarin.Forms.Platform.Android.VisualElementRenderer<TElement>.SetPackager(VisualElementPackager packager)<b5b1173f4d49442b898c45e26ae39e48>:0
Xamarin.Forms.Platform.Android.VisualElementRenderer<TElement>.SetElement(TElement element)<b5b1173f4d49442b898c45e26ae39e48>:0
Xamarin.Forms.Platform.Android.VisualElementRenderer<TElement>.SetElement(VisualElement element)<b5b1173f4d49442b898c45e26ae39e48>:0
Xamarin.Forms.Platform.Android.Platform.CreateRenderer(VisualElement element, Context context)<b5b1173f4d49442b898c45e26ae39e48>:0
Xamarin.Forms.Platform.Android.AppCompat.Platform.ModalContainer.Platform(Context context, Page modal)<b5b1173f4d49442b898c45e26ae39e48>:0
Xamarin.Forms.Platform.Android.AppCompat.Platform.PresentModal(Page modal, bool animated)<b5b1173f4d49442b898c45e26ae39e48>:0
at Xamarin.Forms.Platform.Android.AppCompat.Platform+<Xamarin-Forms-INavigation-PushModalAsync>d__30.MoveNext () [0x0004a] in <b5b1173f4d49442b898c45e26ae39e48>:0
Xamarin.Forms.Application.NavigationImpl.<OnPushModal>d__3.MoveNext()<1feef6e00a314921bf9a29876c83b540>:0
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()<896ad1d315ca4ba7b117efb8dacaedcf>:0
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<896ad1d315ca4ba7b117efb8dacaedcf>:0
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<896ad1d315ca4ba7b117efb8dacaedcf>:0
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)<896ad1d315ca4ba7b117efb8dacaedcf>:0
System.Runtime.CompilerServices.TaskAwaiter.GetResult()<896ad1d315ca4ba7b117efb8dacaedcf>:0
at CCEMobileApp.Controls.SignatureButton+<<-ctor>b__0_0>d.MoveNext () [0x00082] in <6833761041514ac3b59b9a5c6a7607cd>:0
Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0()<e975227ac8644a30bb0866117325de0d>:0
Java.Lang.Thread.RunnableImplementor.Run()<e975227ac8644a30bb0866117325de0d>:0
Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this)<e975227ac8644a30bb0866117325de0d>:0
at (wrapper dynamic-method) System.Object:57fd9798-98fa-4853-a141-6a3eb2787dc4 (intptr,intptr)
mono.java.lang.RunnableImplementor.n_run(Native Method)
mono.java.lang.RunnableImplementor.run()RunnableImplementor.java:30
android.os.Handler.handleCallback()Handler.java:789
android.os.Handler.dispatchMessage()Handler.java:98
android.os.Looper.loop()Looper.java:164
android.app.ActivityThread.main()ActivityThread.java:6809
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.Zygote$MethodAndArgsCaller.run()Zygote.java:240
com.android.internal.os.ZygoteInit.main()ZygoteInit.java:767`

Thanks.

**Comment by starking1017** [comment]
For some reason, I reinstall nuget package and it no issue now. I am not sure does it really resolve or not. Thanks in advance.

**Comment by andersmandersen** [comment]
Had the same problem. Reinstalling nuget packages and removing all bin and obj folders resolved the issue.

**Comment by mattleibow** [comment]
Things changed quite a bit at this time so a clean build should fix it. One of the major changes was to go from requiring some Platform.Init() call to not needing it - the code structure changed a bit, but sometimes the build cached the old assemblies.
