### ISSUE TITLE
Null Reference Exception in Xamarin.Forms

### ISSUE THREAD

**Issue by kartiksolanki** [xamarin/SignaturePad#114]
I am trying to use SignaturePadView in my Xamarin.Forms project. I have written something like this:

var signaturePad = new SignaturePadView()
            {
                HeightRequest = 200,
                BackgroundColor = Color.FromHex("#FBFBFB"),
                SignatureLineColor = Color.Gray,
                StrokeColor = Color.Black,
                StrokeWidth = 5,
                CaptionText = "sign above this line",
                CaptionTextColor = Color.Gray,
                ClearText = "clear signature",
                ClearTextColor = Color.Gray

            };      

And then I have a Capture button, on whose click, I am calling these:
      var imageStream = await signaturePad.GetImageStreamAsync(SignatureImageFormat.Png);
      var mstream = (MemoryStream)imageStream;
      mstream = new MemoryStream(mstream.ToArray());

I am getting System.NullReferenceException on the first line " var imageStream = await signaturePad.GetImageStreamAsync(SignatureImageFormat.Png);".

Any idea, what am I doing wrong?

**Comment by krime81** [comment]
did you manage to resolve this ?
