### ISSUE TITLE
How the access the image path from memory stream?

### ISSUE THREAD

**Issue by kartiksolanki** [xamarin/SignaturePad#115]
Hi,
I am using the SignaturePad plugin to capture the signature and I am saving in memory stream like:

var imageStream = await signaturePad.GetImageStreamAsync(SignatureImageFormat.Png);
var signatureMemoryStream = new MemoryStream();
imageStream.CopyTo(signatureMemoryStream);
byte[] data = signatureMemoryStream.ToArray();

Now, what I need to do is attach that signature image in an email. So for that, I am using the Cross-Messaging NuGet plugin which allows me to attach the image inside email. So, I need a path of the Signature image. So any idea, how can I save the signature in my local Xamarin PCL shared project path and get the path for the image?

**Comment by mattleibow** [comment]
The signature image from `GetImageStreamAsync` is in-memory so it does not have a path.

To get a path, you will first have to save it to the file system. There are libraries like "PCLStorage" for PCL, but you can use the `System.IO` namespace if you are using .NET Standard (I would strongly suggest switching to .NET Standard).
