### ISSUE TITLE
Bindable signature image

### ISSUE THREAD

**Issue by MaxFe** [xamarin/SignaturePad#120]
Hello, 
it would be nice to have a bindbale signature. This could be a stream/byte[] or what is more convenient in your opinion.

It would also be great to have ImageConstructionSettings as a bindable property. Which has an effect on the bound signature.

**Comment by mattleibow** [comment]
This is going to be very hard to do in a performant manner. This is the same with the `Points` and `Strokes` properties. The image and points update each time the stroke is in the process of drawing. This could mean that a simple line may generate thousands of events.

A much better way would be to watch the `StrokeCompleted` event and then just ask for a new image each time. This is still quite heavy as if there are many strokes, the control has to first render the image or collect the points.

I am going to close this issue as I don't think this will be coming anytime soon, but if you feel this is a major issue and someone can maybe offer some ideas as to how to do this in a performant manner, just reopen.

**Comment by mattleibow** [comment]
Moving this discussion to the more general https://github.com/xamarin/SignaturePad/issues/133 issue.
