### ISSUE TITLE
IsEnabled is not working

### ISSUE THREAD

**Issue by MaxFe** [xamarin/SignaturePad#121]
Hello, 
I have some problems to bind IsEnabled (SignaturePadView.IsEnabled={Binding IsEnabled} and SignaturePadCanvas.IsEnabled={Binding IsEnabled}). Both won't work. I've made the experience, that BindableProperties with primitive type need a PropertyChanged implementation. That may be the cause.

**Comment by mattleibow** [comment]
That very well might be the case. Bindings only work if the property also raises a `PropertyChanged` event.

If this still does not work, be sure to re-open and let me know what platform and version you are using.
