### ISSUE TITLE
Signature does no appear until stylus is lifted on some devices

### ISSUE THREAD

**Issue by simonfanz** [xamarin/SignaturePad#122]
I'm using signaturepad 2.3 in a xamarin forms app, but have noticed an issue on devices using a stylus in that the signature does not show up as the user signs, but only shows up when they lift the stylus. It works fine when the user signs with their finger though.  Any idea why the stylus might behave differently?

**Comment by simonfanz** [comment]
Oddly if I roll SignaturePad and SignaturePad.Forms back to 2.0 in just the android project this fixes it (2.1 breaks it) - so my naive assumption is something may have changed in 2.1 that caused this issue?

**Comment by tsantinho** [comment]
Some problem here, there are any solution please?

**Comment by PatGet** [comment]
Rollback to 2.0 has some mayor performance issues for me. Is this activly developed or should i just look around for another control or fork and host myself?

**Comment by aftersow** [comment]
I seriously doubt it... More of a temp workaround than a permanent measure.

It also has the disadvantage of not working with scrollviews, attempting to
write  vertically results in scrolling.

Got some guys looking into a fix... If we get anywhere, I'll post back

**Comment by mattleibow** [comment]
This was fixed and merged into the new v3.0 preview.

**Comment by mattleibow** [comment]
Released the first preview of v3.0 with loads of improvements:
https://github.com/xamarin/SignaturePad/releases/tag/v3.0-preview-77

**Comment by tsantinho** [comment]
Thank you very much, problem solved 👍
