### ISSUE TITLE
Clearing a zone

### ISSUE THREAD

**Issue by jordixip** [xamarin/SignaturePad#125]
Hello, 

I am trying to find the way to clear a zone... and tried with 

```csharp
private void Borrador(object sender,EventArgs e)
{
    // test
    if (signature.StrokeColor==Color.Black) signature.StrokeColor = Color.White;
    else signature.StrokeColor = Color.Black;
}
```

but it is not doing the thing I need due to it is clearing all the image.

What could I do it?

After pressing a button, I need to draw with Color.white, and on other case draw with Color.black.

Another thing, is how could I change the arrow for another image?

Thank you

**Comment by mattleibow** [comment]
Unfortunately this feature is not supported in the `SignaturePadView` as the `StrokeColor` property set the color for all the strokes.

If you want to handle multiple colors, feel free to open a new issue for this specifically. However, this probably won't come too soon as this is not really what this control is designed for.

With regards to the little arrow, you can change the text using the `PromptText` property. This is just a string and can really be anything.

**Comment by mattleibow** [comment]
This is really a duplicate of https://github.com/xamarin/SignaturePad/issues/125
