### ISSUE TITLE
Missing lines in signature image

### ISSUE THREAD

**Issue by AvBrenk** [xamarin/SignaturePad#14]
I am facing some trouble with this component. 90% of the time, the resulting signature (which I get using the signaturepad.GetImage() method) is missing some lines.

For example, if I sign by drawing XAMARIN as the signature, in the app it all looks perfect, no lines missing (see below):

![screenshot-signature](https://cloud.githubusercontent.com/assets/10826220/6016477/cb2cb9c6-ab82-11e4-9df2-df9fd7953bf7.jpg)

but in the resulting image, a lot of lines are missing (see below)

![signature-result](https://cloud.githubusercontent.com/assets/10826220/6016491/f966a1a8-ab82-11e4-92ee-e77812a9844c.png)

**Comment by waeltken** [comment]
Hi!
I am using aritchie's version of the signature pad https://github.com/aritchie/acr-xamarin-forms
It's based on the Xamarin SignaturePad and the same problem is visible there, some strokes are lost randomly on the actual drawing area.

**Comment by loewendan** [comment]
I'm having all kinds of problems when printing letters especially with letter disappearing entirely.  Ie.  I'll print the name R o b and after the b is done - the o disappears.  See the video in this link for an example.  

https://www.dropbox.com/s/m3mrt83qzka702b/xamarinsignaturepadissue.mov?dl=0

**Comment by napoleond** [comment]
I have created a fork that fixes this issue in iOS: https://github.com/napoleond/SignaturePad

It's three lines of code. PR is here: https://github.com/xamarin/SignaturePad/pull/17

I assume that a similar change is possible in Android code, although I haven't tried yet.

**Comment by fcogutierrez** [comment]
Hi @napoleond , how can I ouse your fork? I have the same issue.

**Comment by napoleond** [comment]
@fcogutierrez the simplest way is probably just to clone the repo and add the project(s) to your solution (in Visual Studio or Xamarin Studio). Usage is identical to the "official" component.

**Comment by mattleibow** [comment]
This is fixed in v2.0
