### ISSUE TITLE
How to load Byte array to SignaturePad xamarin forms

### ISSUE THREAD

**Issue by pmd23** [xamarin/SignaturePad#145]
Hi Team,
I am using this control into my Xamarin Form Project. I am saving the signature into backend sql server in byte array format.

![signaturepad](https://user-images.githubusercontent.com/2580866/44190493-b87f5200-a144-11e8-9a3a-a06cf25ed800.png)
so for these things go well thanks for such wonderful control.

issue start from here.
How I can load this `AttachSignature `array back to `Signature Pad`. might be is wil be duplicate but I am not able to find out solution in open as well as in close threads for Xamarin Forms.

**Comment by blwhttngtn** [comment]
I'm also interested! Thank you

**Comment by nativenolde** [comment]
@pritish5 Did you check out this sample app? i believe it has implemented a feature to load persisted signatures...

https://github.com/xamarin/SignaturePad/tree/master/samples/Sample.Forms/Samples
