### ISSUE TITLE
CaptionText not showing

### ISSUE THREAD

**Issue by mahendraleo4** [xamarin/SignaturePad#155]
I am using v2.3.0 of signaturePadView fo native android project in xamarin.
My whole project in landscape mode .
on signaturePadView CaptionText and prompt not showing
my xml ->
<xamarin.controls.SignaturePadView
              android:id="@+id/signatureTheripist"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              android:layout_margin="1dp"     
              android:background="@color/White" />

class code->
 signaturePadView.SetBackgroundColor(Color.ParseColor(Resources.GetString(Resource.String.KEY_WHITE)));
            signaturePadView.StrokeColor = Color.Black;
            signaturePadView.ClearLabel.Text = "";
            signaturePadView.StrokeWidth = 7;
            signaturePadView.ClearLabel.SetBackgroundResource(Resource.Drawable.delete);
            signaturePadView.ClearLabel.Visibility = ViewStates.Visible;
            signaturePadView.CaptionText = "Sign here.";
            signaturePadView.Caption.Visibility = ViewStates.Visible;
            signaturePadView.SignaturePromptText = "X";
            signaturePadView.ClearLabel.Click += ClearLabel_Click;

**Comment by Weldryn** [comment]
Try to update to latest

**Comment by mahendraleo4** [comment]
Thank you @Weldryn update SOLVE my issue.

**Comment by VladislavAntonyuk** [comment]
@mahendraleo4 Please close the issue
