### ISSUE TITLE
Localizing Clear Label?

### ISSUE THREAD

**Issue by moflaherty** [xamarin/SignaturePad#25]
Hi! I don't know if this is possible already, so if this can be done, I would appreciate some hints how to do it. We are localizing our application and the _ClearLabel_ property is read only. Is there a way to set that value? Or can this be added to the wish list? Thanks!

**Comment by mattleibow** [comment]
You should be able to change the text as well as access the label itself directly.

`ClearLabel` is `UIButton` and `ClearLabelText` is the string value.

**Comment by moflaherty** [comment]
Sure; maybe stated another way, I would like to be able to get/set any text properties without the need to recompile my own custom version. I am using Android and iOS.

**Comment by hemantksh** [comment]
For the Xamarin.Forms plugin, there is a ClearText property which you can use:

<signature:SignaturePadView x:Name="signaturePad" AutomationId="signaturePad" HorizontalOptions="FillAndExpand"
				VerticalOptions="FillAndExpand" Margin="0,-8,0,-8" BackgroundColor="{DynamicResource SignatureBackground}"
				CaptionText="" CaptionTextColor="Transparent" **ClearText="{i18n:Translate sig_clear}"**
				ClearTextColor="{DynamicResource PrimaryBlue}" PromptText="" PromptTextColor="Transparent"
SignatureLineColor="Transparent" StrokeWidth="3" StrokeColor="{DynamicResource SignatureStroke}" />

**Comment by mattleibow** [comment]
Closing this now since @hemantksh provides the correct way to customize the UI.
