### ISSUE TITLE
Signature pad inside scroll view is not Working

### ISSUE THREAD

**Issue by sylendra7** [xamarin/SignaturePad#26]
While drawing the signature pad inside the scroll view it is not working

**Comment by Anand-Dubey** [comment]
I am also facing the same signaute pad issue. In my android application, there is lot of controls on the screen. That's why screen is scrollable. And when I am trying to sign on signature pad screen is scrolling. How I can stop the scrolling of the screen when signing on the signature pad?

**Comment by swellfr** [comment]
Same issue for me.

**Comment by appana-anil** [comment]
Hi swellfr,

The fix you mentioned is it for xamarin android or xamarin forms?

**Comment by swellfr** [comment]
It's Xamarin Android.

If you want to do the same in iOS, you have to override the HitTest function and check if any of your parent is a scroll view.

**Comment by Soulinator** [comment]
Hi,

Could anyone explain to me how to use the android fix?

I've got an scrollview with in it a linearlayout and at the bottom of it i have the signature pad.

Thanks in advance

**Comment by mattleibow** [comment]
I will look into implementing this.

**Comment by mattleibow** [comment]
Linking in #22
