### ISSUE TITLE
Not able to retrieve the image from signaturepad in android.Getimage method not returing the stream properly.

### ISSUE THREAD

**Issue by ibrahimAJ** [xamarin/SignaturePad#28]
Stream stm = signatureView.sig.GetImage(ImageFormatType.Png);
               img.Source = ImageSource.FromStream(() => { return stm; });

stm is not properly recieved so source for image is not working.

**Comment by mattleibow** [comment]
This was a bug in that the stream was not being rewound.

Fixed in v1.5.
