### ISSUE TITLE
Setting the SignaturePrompt property has no effect

### ISSUE THREAD

**Issue by mikebluestein** [xamarin/SignaturePad#3]
This snippet:

    public override void ViewDidLoad ()
    {
        base.ViewDidLoad ();

        View.BackgroundColor = UIColor.White;
    	
        var signature = new SignaturePadView (View.Frame) {
            StrokeWidth = 3f,
            SignaturePrompt = new UILabel {Text="foo"},
        };

        View.AddSubview (signature);
    }

produces this screenshot (label at beginning of signature line is missing):

![missing signatureprompt](https://cloud.githubusercontent.com/assets/164170/2832918/20de75c0-cfca-11e3-88d1-0d4296415ac3.png)

**Comment by mattleibow** [comment]
I don't think we want to do this. @bholmes can comment, but I have made the subview assignments private. It makes it not-so-nice for inline assignment, but then I cannot properly control my own subviews.

**Comment by bholmes** [comment]
agree
