### ISSUE TITLE
How to avoid writing signature in CaptionText?

### ISSUE THREAD

**Issue by spathipati** [xamarin/SignaturePad#36]
Hi,

I am using Xamarin Forms and was able to writing signature in CaptionText, how to prevent this?

**Comment by mattleibow** [comment]
As of today, the entire signature area is writeable. I will investigate an option to clip the signature so that it doesn't allow writing over the labels/buttons

**Comment by mattleibow** [comment]
I spent some time thinking about this and I am adding some features in the next version that may be useful. In v2.0 there will be a "chrome-less" signature pad which can be used. I don't think there will be an option to clip the signature around existing buttons. If this is desired, you can always change the button text or background color which will obscure the underlying signature.

As was mentioned in the linked (#61) issue, you can do something like:
> You may set ClearText to empty string so it does not display on the pad and add a CLEAR SIGNATURE button below the pad.
