### ISSUE TITLE
Is there a way to clear the signature pad programmatically? 

### ISSUE THREAD

**Issue by rhfrench** [xamarin/SignaturePad#38]
I'm using the forms version of the signature pad and it doesn't seem to have a way to hide the clear label and clear the signature pad in code like this.padView.Clear()? Anyway this could be done?

**Comment by Contract16** [comment]
Has anyone found a solution for this?

**Comment by rhfrench** [comment]
` public void Clear_Clicked(object sender, EventArgs e)
        {
            InitializeComponent();
        }`

**Comment by rhfrench** [comment]
Calling initializeComponent() will do the trick until they update the signaturepad properly

**Comment by Contract16** [comment]
Thanks, I'll use that for now until they update (or I fork and do it myself)

**Comment by mattleibow** [comment]
That will probably cause issues later on. The `Clear()` method should be available in v1.5.
