### ISSUE TITLE
Unable to load existing points with Xamarin.Forms for Android & iOS

### ISSUE THREAD

**Issue by lanarchyste** [xamarin/SignaturePad#40]
Hello,

I use version 1.4.0 of SignaturePad with Xamarin.Forms (02.03.2127) for Android projects (Xamarin.Android 6.1.2.21) and iOS (Xamarin.iOS 10.0.0.6).

When I load my page, and I want to reload signature, nothing appears (whether on Android or iOS).

Here is the code used:
`padView.Points = signaturePoints;`

The variable "signaturePoints" is a point list, saved in the first signature. The list contains several points (over 3000).

Is it normal that nothing appears? Is there another way?

Thank you.

Best Regards.
Julien.

**Comment by mattleibow** [comment]
This is not normal... Are you able to try this with a later version? Maybe there was a bug that was fixed later on.

Closing now as this is old, but reopen if this is still an issue.

**Comment by lanarchyste** [comment]
Hi

I test with the latest version (1.5.1) and loading existing points still does not work.

I use version 2.3.4.231 of Xamarin.Forms
