### ISSUE TITLE
Pad doesn't work on iOS device, does in simulator

### ISSUE THREAD

**Issue by gmeredith** [xamarin/SignaturePad#41]
I am using SignaturePad in a PCL project. Pad works great on Android, no issues. I can use the Pad on iOS simulator - 6s 9.3. I can't verify image capture as I have GPS location requirements coded in app which is not supported in simulator - at least MacInClouds. When I deploy it to App store/test flight and run on my personal phone the signature pad displays. I'm running 6s 9.3.4 on my phone. The signature "X", line and clear don't show up. The pad doesn't even respond to my signing with my finger.

**Comment by gmeredith** [comment]
I have determined that if I remove the following from code (from my ".iOS" project in AppDelegate.cs) and run in the simulator I get the same non-interactive, line & "X" missing Pad on the simulator.
var t = typeof(SignaturePad.Forms.iOS.SignaturePadRenderer);
I may be over simplifying but that means I need some sort of Initialization for the Pad in the AppDelegate.cs for the Pad to work. I can't seem to find an example of the Pad being initialized.
Thoughts?

**Comment by ckimes89** [comment]
If the signature pad is not loading on your iOS 10 device, I have found a workaround. The problem is with the linker (and presumably the linker ignoring the `Preserve` attribute). Add this code somewhere in your project, I'd recommend in the `AppDelegate.FinishedLaunching` method:

```
var renderer = new SignaturePadRenderer();
var view = new SignaturePadView();
var otherView = new SignaturePad.Forms.SignaturePadView();
```

**Comment by gmeredith** [comment]
Chad - Thanks! It worked. I now have the fancy "finger" signature instead of the lame "type your full name" entry box on my iOS device. I was able to get it to work with the following 2 lines in the FinishedLaunching event.

SignaturePad.Forms.iOS.SignaturePadRenderer renderer = new SignaturePad.Forms.iOS.SignaturePadRenderer();
SignaturePad.Forms.SignaturePadView signature = new SignaturePad.Forms.SignaturePadView();
