### ISSUE TITLE
UWP Support

### ISSUE THREAD

**Issue by InquisitorJax** [xamarin/SignaturePad#44]
Is UWP supported?
Looks like Windows Phone is (perhaps deprecate this in favor of UWP?)

**Comment by TonyHenrique** [comment]
Also a Xamarin.Forms Version would be a good option.

**Comment by saramgsilva** [comment]
There is any date to support it in UWP apps?

Thanks

**Comment by InquisitorJax** [comment]
There is an unfinished [pull request](https://github.com/xamarin/SignaturePad/pull/47) for UWP - not sure how far the implementation got.
Little disappointed with SignaturePad - doesn't look like it's actively supported anymore. 
The Xamarin Forms is there - but a little buggy. Had to fork to fix a GetImageFromStream jpg format for Android.

**Comment by maxim-tkachenko** [comment]
[this](https://github.com/xamarin/SignaturePad/pull/47) pull request doesn't work for me. I've implemented my own [version](https://github.com/maxim-tkachenko/XamarinSignaturePad/tree/uwp).

**Comment by gtbuchanan** [comment]
UWP support has been added in version 1.5.0, so this ticket can probably be closed now. However, I noticed a bug on navigation (see #59).

**Comment by mattleibow** [comment]
This issue is now fixed in v1.5.1
