### ISSUE TITLE
LoadPoints(PointF points) not supported in Xamarin Forms

### ISSUE THREAD

**Issue by msmrajesh** [xamarin/SignaturePad#45]
Hi,

Why is this method LoadPoints(PointF points) not supported in PCL. I am able to make the Points work to retrieve an array of points but unable to reload it on the signature pane in another screen.

Is there any working example that supports this scenario.

Thanks,

Rajesh.

**Comment by mattleibow** [comment]
In the Xamarin.Forms version, the `LoadPoints` method has been replaced with the `Points` getter and setter:

```csharp
Point[] points = signaturePad.Points;
signaturePad.Points = points;
```
