### ISSUE TITLE
SignaturePad.Forms GetImageStream returns an image with transparent background

### ISSUE THREAD

**Issue by mattman624** [xamarin/SignaturePad#46]
It would be great to have an option to use the background color, however that is not an option in Forms.  The transparent background can make it difficult to see the signature.

**Comment by InquisitorJax** [comment]
This would also solve a current issue with Forms.Android creating a black image when using jpg format in conjunction with GetImageAsStream().
Adding a UseBackgroundColor bool flag to ImageStreamRequestedEventArgs and then using it in the resulting GetImage() platform call solves this.

**Comment by mattleibow** [comment]
This is related to #53 and #51. This should now be possible (in v2.0)
