### ISSUE TITLE
Signature line too small

### ISSUE THREAD

**Issue by Clancey** [xamarin/SignaturePad#5]
The signature line is way to far down, it should be percent based rather then a fixed position. And it should be adjustable. When you do it full screen on an iPad its just seems wrong:

https://www.dropbox.com/s/lkl7qndro7vzm39/Screenshot%202014-04-29%2011.07.44.png

**Comment by mattleibow** [comment]
This should no longer be a problem after #31. the line will always be above the caption, which can be sized. Also, the line thickness can now be changed using a single property, or by accessing that view directly.

**Comment by gtbuchanan** [comment]
@mattleibow How exactly can the caption be sized? I see #31 is closed, but I don't see an API in master for setting the caption size. Are you referring to Xamarin iOS only or Xamarin Forms?

**Comment by mattleibow** [comment]
This was actually only for the native versions.

I see there is not much customization support for Xamarin.Forms, so I will add more hooks in the new version.

**Comment by mattleibow** [comment]
Re-wrote the Xamarin.Forms views in ba653e553df3cc0b78dcc34fe0789ae3c0b785c3

 - `SignaturePadCanvasView` is now wrapped as this is chromeless
 - `SignaturePadView` is now a fully Xamarin.Forms view so that it can be better customized as there is access to the individual views
