### ISSUE TITLE
Xamarin.Forms Version Android, iOS, UWP

### ISSUE THREAD

**Issue by TonyHenrique** [xamarin/SignaturePad#50]
Is there a Xamarin.Forms version of Signature Pad?
I don´t want to add the code for it on every iOS, Android, UWP Project of the solution.
This is a issue that should be adressed.

**Comment by Seichis** [comment]
It is already addressed... Add the nuget packages to the pcl and the platforms that you want to use and try it out. Check the samples.

**Comment by mattleibow** [comment]
There is support for Xamarin.Forms.

UWP support was just added.
