### ISSUE TITLE
Add args to GetImageAsStream to give Forms feature parity

### ISSUE THREAD

**Issue by InquisitorJax** [xamarin/SignaturePad#51]
Currently on a platform level one can use GetImage method on the platforms with multiple arguments. Would be great if GetImageAsStream() implementation in Forms implementation gave the same options, or at least a subset (for example color cannot be made cross platform - perhaps the option to use the background color property as fill color instead of transparent would suffice here)

**Comment by mattleibow** [comment]
Fixed in 713ecbd62ec20ec0b91e9fbf2658161d6159b9c4
Related to #53
