### ISSUE TITLE
Add shouldCrop argument to GetImageAsStream

### ISSUE THREAD

**Issue by steve34581133** [xamarin/SignaturePad#53]
Previous version of GetImage method had a shouldCrop argument. I believe that GetImageStreamAsync method does not the signature image is always cropped. After upload to a central database server my captured signatures are used in a variety of different environments and handling the cropped signature image has become problematic.

Would appreciate a shouldCrop argument to GetImageStreamAsync method to allow the app to decide whether image should be cropped.

**Comment by mattleibow** [comment]
This issue may have been meant for the native views, which has the overloads in a previous commit.
