### ISSUE TITLE
Yoga Book

### ISSUE THREAD

**Issue by Premizlaus** [xamarin/SignaturePad#56]
Working with lenovo yoga book pad??

**Comment by mattleibow** [comment]
What do you mean?

**Comment by Premizlaus** [comment]
i have to transfer drawing from lenovo pad

**Comment by mattleibow** [comment]
You can save the image using `GetImage(..)` or `GetImageStream(...)`.

This will return an image or stream that you san save to disk or upload.

**Comment by Premizlaus** [comment]
Yes but when drawing on pad nothing happens on screen. This is the problem. Signature on screen works perfectly
