### ISSUE TITLE
[Android] Should not be able to draw over the clear label

### ISSUE THREAD

**Issue by bentmar** [xamarin/SignaturePad#61]
At least not so that i covers with "ink"

**Comment by hemantksh** [comment]
The component now exposes the Clear() method so you can use a button external to the component to clear the pad. You may set ClearText to empty string so it does not display on the pad and add a CLEAR SIGNATURE button below the pad.

**Comment by mattleibow** [comment]
This is related to #36 (caption label). In v2.0 there will be a "chrome-less" signature pad which can be used. I don't think there will be an option to clip the signature around existing buttons. If this is desired, you can always change the button text or background color which will obscure the underlying signature.
