### ISSUE TITLE
SignaturePad (Xamarin.Forms) not rendering on iOS

### ISSUE THREAD

**Issue by jorisM96** [xamarin/SignaturePad#62]
This works perfectly on Android but it doesn't render on iOS (nor on real device, nor on simulator).
I already tried this: [https://github.com/xamarin/SignaturePad/issues/43](url) but there was no solution that worked for me.
I use Xamarin Forms version 2.3.3.193 and version 1.5.1 for SignaturePad.
Someone with the same problem?

Update: Solution found

**Comment by juanmagil** [comment]
Hi, how did you solve it?
