### ISSUE TITLE
Not working on Android with Forms

### ISSUE THREAD

**Issue by zanesc** [xamarin/SignaturePad#66]
I just updated to 2.0 and iOS works perfectly but android does not. Android worked fine before upgrade. I will revert to an older version for now but the 2.0 update brought a few things that i really liked so i really hope to get this working soon. I am building a Forms app. I have tried cleaning my project and rebuilding.

I just get a blank view where the signature pad should be.

Here is the code i use to load it. 

`<signature:SignaturePadView
                x:Name            ="padView"
                BackgroundColor   ="White"
                CaptionText       ="Sign here."
                CaptionTextColor  ="Black"
                ClearText         ="Clear"
                ClearTextColor    ="Black"
                PromptText        ="X"
                PromptTextColor   ="Black"
                SignatureLineColor="Black"
                StrokeWidth       ="3"
                StrokeColor       ="Black"
                VerticalOptions   ="Center" />`

iOS:
![ios](https://cloud.githubusercontent.com/assets/1435517/25922217/4e0b0b9a-35a6-11e7-91ea-f77082ec73ae.png)

Android:
![android](https://cloud.githubusercontent.com/assets/1435517/25922216/4dfe26f0-35a6-11e7-8f3c-9ceacd8eb604.png)

**Comment by zanesc** [comment]
Cleaned project, removed bin and obj files, restarted computer, restarted android tablet and then it worked. Closing.

**Comment by mattleibow** [comment]
Great to see you got it working. Typically if you are having issues with a whole control not displaying, then there is a problem with the app loading the renderers.

Sometimes when doing a major assembly change (eg: installing new NuGets) the Android fast-deploy system gets out of sync. To reset this, you can usually get away with manually uninstalling the app from the device.

And, be sure to give us any feedback that you may have on this new release.

And, just in case you don't know... we have a new UI element `SignaturePadCanvasView` that is a chrome-less element. No buttons and labels. If you want to use your own custom signature UI, you can use this new element and not have to deal with our defaults!
