### ISSUE TITLE
Can we add an 'OnClear()' event handler?

### ISSUE THREAD

**Issue by Hangarspace** [xamarin/SignaturePad#80]
When used in conjunction with 'StrokeCompleted' to count the number of points we can implement some simple signature validation logic.

**Comment by mattleibow** [comment]
Thanks for the suggestions, I will look into getting this in for the next release.

**Comment by LaBoss** [comment]
Hello are there any predictions to be available in the nuget?

Thanks

**Comment by mattleibow** [comment]
I hope to get this out soon, can't say exactly, but should be this month.
I just have a few issues to close for v2.2

**Comment by LaBoss** [comment]
Nice thanks
