### ISSUE TITLE
Performance Issue: Ressources not being released correctly on iOS

### ISSUE THREAD

**Issue by fl034** [xamarin/SignaturePad#81]
I use the SignaturePad for getting signatures, but also as a easy note pad, that has the ability to add pages to it.

When I have drawn really much the app slows down extremely. 
Would be okay if it would release those resources when closing the ViewController, but it doesn't.

When I'm opening a new page, so a fresh SignaturePadCanvasView-Object, the performance is still bad.

I've tried to do a forced Garbage Collection and of course setting the SignaturePadCanvasView-object = null, but both didn't help.

I'm using an iPad Air 2 on iOS 10.3.2 with SignaturePad 2.1.0

**Comment by fl034** [comment]
Sorry, this issue was related to changes I did myself on the code.

**Comment by mattleibow** [comment]
Glad to hear you managed to find out what the issue was.
