### ISSUE TITLE
Android: Error Forms.Init TypeLoadException

### ISSUE THREAD

**Issue by Dabbel** [xamarin/SignaturePad#82]
I just added the SignaturePad to my project and get this error:

System.TypeLoadException: Could not load type SignaturePad.Forms.SignaturePadCanvasRenderer while decoding custom attribute: (null)

I already checked the sample projects and didn't see any difference to my project.

**Comment by Dabbel** [comment]
Version 1.5.1 works without problems, with any version greater than 1.5.1 i get the error

**Comment by Dabbel** [comment]
Have done multiple things at once, now it works.
Deleted all copied code, added the forms nuget package, delete every bin and obj folder, run clean solution, run rebuild

**Comment by Dabbel** [comment]
Visual Studio cache problem

**Comment by mattleibow** [comment]
I see you were doing some testing. Is this still an issue? If so, are you able to provide more details as to what you were doing?

You could try deleting the bin/obj folders - and maybe the packages folder. I have not seen this error myself.
