### ISSUE TITLE
Maintain offset from point 1.1

### ISSUE THREAD

**Issue by Gilbertvan** [xamarin/SignaturePad#84]
In our application we place the SignaturePad over an image, this could also be the background.
After signing we want to merge this image and the signature.

As it's now a frame will be made around the signature and i cannot place it back on the exact location of the image.

Can this be enhanced?

**Comment by mattleibow** [comment]
Thanks for opening this issue. I will investigate exposing this to the world. Right now, the logic is in place to control the padding - it is just hidden from the world and defaults to 5 units (it should be normal pixels).

**Comment by Gilbertvan** [comment]
Thanks Matthew. 
Either correct padding or a merge with the background image (that's asking for a lot) would be great enhancements.

**Comment by Gilbertvan** [comment]
Hi Matthew, 

I see your code changes but wonder how to implement this. 
Please consider this code :
`        <Grid>
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="*" />
            </Grid.ColumnDefinitions>
            <Grid.RowDefinitions>
                <RowDefinition Height="*"/>
            </Grid.RowDefinitions>
            <Image x:Name="image" RelativeLayout.WidthConstraint="{ConstraintExpression Type=RelativeToParent, Property=Width}"
          RelativeLayout.HeightConstraint="{ConstraintExpression Type=RelativeToParent, Property=Height}" />
            
            <forms:SignaturePadView Grid.Row="0" Grid.Column="0" x:Name="DrawingPad"
                                HeightRequest="150" WidthRequest="240"
                                BackgroundColor="Transparent"
                                ClearText="Clear" ClearTextColor="Red"
                                        CaptionText=" " CaptionTextColor="Blue"
                                SignatureLineColor="Transparent" StrokeColor="Red" StrokeWidth="2" />
        </Grid>`

Once some button is clicked on my page the image and result from the signaturePad are merged.
When merged the signature needs to be on the same position as where it was on the screen.
How do i determine the offset from point 0.0 of where the signature starts?

Thanks in advance.

**Comment by mattleibow** [comment]
You can turn off the crop, then you just need to position the image at 0,0. Either the parameter `shouldCrop` or the settings property `ShouldCrop` should work fine.

**Comment by jBijsterboschNL** [comment]
Hi @mattleibow, after installing the new version (2.2) the ShouldCrop settings works fine on Android and iOS, but on Windows it doesn't seem to work. Could you investigate this?
