### ISSUE TITLE
Why Doesn't SignaturePadCanvasView implement INPC?

### ISSUE THREAD

**Issue by zacglenn** [xamarin/SignaturePad#90]
I'm using SignaturePad control in an Xamarin.Forms MVVM patterned project. I am trying to bind to the Points member of the SignaturePadView in the xaml View. Within the ViewModel, it doesn't appear that the Points member is ever being set.

It's also been identified that SignaturePadCanvarView doesn't implement INotifyPropertyChanged. Is this by design? If so, how may I bind to the SignaturePadView or bind to the Points member to access it in the ViewModel?

**Comment by mattleibow** [comment]
This is now something in v3.0

**Comment by mattleibow** [comment]
Released the first preview of v3.0 with loads of improvements:
https://github.com/xamarin/SignaturePad/releases/tag/v3.0-preview-77
