### ISSUE TITLE
How to convert byte[] to List<Point> to load existing image?

### ISSUE THREAD

**Issue by kpatwa** [xamarin/SignaturePad#91]
I am storing signature in base64 format and want to reload image using same data but I am unable to convert byte[] to list of point. 

Is below code only way to load data in signaturePad ? 
signature.Points = points.

Any help?

**Comment by mattleibow** [comment]
You can't mix the points and the image.

If you are saving the image using `GetImage`, then this is a bitmap. You can, however, save and load the points using the `Points` property. This returns a collection of point structures.

**Comment by kpatwa** [comment]
Thanks for the reply. I have created a custom control like below:

<StackLayout Orientation="Horizontal">
        <Image x:Name="ImageControl" BackgroundColor="Transparent" IsOpaque="True" />
        <Button x:Name="ButtonControl" Text="Click to Sign" Clicked="ButtonControl_OnClicked" />
</StackLayout>

Where I am able to load base64 string in ImageControl using ImageSource property. So now I am using SignaturePad only to sign and not loading existing stored signature.

Thanks.
