### ISSUE TITLE
Enabled property not working

### ISSUE THREAD

**Issue by kodeo** [xamarin/SignaturePad#94]
Neither `SignaturePadView.Enabled` nor `SignaturePadCanvas.Enabled` when set to false prevents drawing on the pad.

**Comment by mattleibow** [comment]
I have found the cause of the issue. This appears to be a "bug" in Xamarin.Forms v2.3, although this is more some weird behavior of Android.

On Android, disabling a layout (such as a grid or stack), the children are not disabled. Wow. Anyway, this was correctly handled in Xamarin.Forms v2.4 (as yet unreleased). I also added a fix for this for the current versions of Xamarin.Forms - which I will remove as soon as v2.4 is released.

For SignaturePad, this is also the case for the native views. I now correctly handle this.

**Comment by freever** [comment]
IsEnabled is working great for me on Android, but not on UWP. I'm using 2.2.0 of SignaturePad.Forms on 2.4.0.18342 of Xamarin.Forms. Setting IsEnabled has no effect.

**Comment by mattleibow** [comment]
I had a look and working on a fix. The reason for UWP not enabling (and the Win8) is that the base type of the signature views are `Grid` and this does not support enabling/disabling the children. My fix will be to wrap the grid in a `ContentControl`.

**Comment by freever** [comment]
Thanks that’s actually super useful to know. I use grid as the base for a lot of my controls, I just hope I remember this when this bites me in the ass one day!
