### ISSUE TITLE
GetImageStreamAsync returning differnt background on ios/androidGetImageStreamAsync

### ISSUE THREAD

**Issue by mannyvw** [xamarin/SignaturePad#96]
GetImageStreamAsync seems to return an image with a black background on android and white on iOS.

StrokeColor is set to black and BackgroundColor is set to white for both on the control which looks great. 

But to get signature to appear in the image at all i have to set the strokecolor to white and then back to black after i call the function. 

Anyway around this?

Thanks

**Comment by mattleibow** [comment]
Is this the native platforms or with Xamarin.Forms?

Also, you can pass in the desired colors when you get the stream, there are a few overloads - one that takes two color parameters and there is even an overload that takes a settings struct with which you can fully customize the image.

**Comment by mannyvw** [comment]
It was on Xamarin.Forms
Sorted using the parameters, completely missed those "10" overloads, good work!
