### ISSUE TITLE
.NET Standard support

### ISSUE THREAD

**Issue by mnusr** [xamarin/SignaturePad#97]
Is there any plans for .NET Standard support?

**Comment by mattleibow** [comment]
That seems like a good plan. We are now. 😄

**Comment by mattleibow** [comment]
Added in https://github.com/xamarin/SignaturePad/commit/f6ba62b213e6231f1270dffba5b311a7eba7be56

**Comment by simonfanz** [comment]
When I try to install to a .net standard project I get:

 Package Xamarin.Controls.SignaturePad 2.3.0 is not compatible with netstandard2.0

Am I misinterpreting this issue? :)

**Comment by mattleibow** [comment]
SignaturePad is still a platform library - so .NET Standard is not really something. But, If you are using Xamarin.Forms, then installing the https://www.nuget.org/packages/Xamarin.Controls.SignaturePad.Forms/ package will work.
